# Generated by Django 3.1.1 on 2020-10-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='adminUser',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='postcode',
        ),
    ]
